version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-events
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - events-net

  backend:
    build: .
    container_name: events-backend
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - events-net
    restart: always

networks:
  events-net:

volumes:
  mysql_data:
